name: Publish Examples

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts
      shell: bash

    - name: Checkout DataVis Repository
      uses: actions/checkout@v4
      with:
        lfs: true
        submodules: recursive
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Replace GITHUB_TOKEN in .npmrc
      run: |
        sed -i "s/GITHUB_TOKEN/$GITHUB_TOKEN/" .npmrc
        cat .npmrc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: make setup

    - name: Build DataVis
      run: make datavis

    - name: Build tests
      run: make tests

    - name: Publish examples
      run: make tests-publish
